# Generated by Django 5.0.1 on 2024-05-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=80)),
                ('age', models.CharField(max_length=50)),
            ],
        ),
    ]
